### ISSUE TITLE
Tapalcatl 2 roadmap

### ISSUE THREAD

**Issue by jwilson8767** [mojodna/tapalcatl-2-spec#1]
This is a consolidated place to organize big-picture todos that cross multiple projects related to Tapalcatl 2.

- [ ] write a list (like this one!) of major missing components to using tapalcatl2 (and opportunities for contribution)
- [ ] write a command line archive creation tool
- [x] define / document archive-level metadata
- [ ] begin a centralized location for user guides / documentation
- [x] write a Tilelive module — for reading/writing/conversion using existing tools (e.g tessera and tl)
- [x] write a Lambda proxy w/ efficient support for larger Tapalcatl 2 archives — to allow Tapalcatl 2 sources to be accessed like normal tile services
- [ ] write documentation for lambda Tapalcatl 2 proxy
- [x] write a reference JS library for retreiveing tiles from a Tapalcatl 2 archive
- [ ] document existing state of tapalcatl-js and outline how more specific implementations could / should use it
- [ ] explore writing  a Service Worker to act as a client-side proxy between existing mapping libraries like Leaflet and Mapbox GL
- [ ] explore writing a plugin for Leaflet or Mapbox GL if Service Worker idea doesn't work out
- [ ] write a complete user guide for building tile archives -> deploying to a static webhost (S3) -> deploying a serverless proxy service (on Lambda) -> and displaying the final service in a web mapping library
- [ ] write a complete user guide for building tile archives -> deploying to a static webhost (S3) -> configuring a web-service based proxy service (on Lambda) -> and displaying the final service in a web mapping library
- [ ] write a Python BytesIO (IOBase / RawIOBase / BufferedIOBase) implementation that makes HTTP Range requests on demand

This post will be updated whenever needed to reflect the direction of the project(s).
